#!/bin/bash
#PBS -V

while getopts l:d:n: option
do
  case "${option}"
    in
      l) snplocations=${OPTARG};;
      d) lzresults_list=${OPTARG};;   
      n) pcolnum=${OPTARG};;
    esac
done

#Load R
 module load R 

#Take the line of metal results

#lzresults=$(awk -v lineno=$PBS_ARRAYID '{if (NR == lineno) print }' $lzresults_list )

cp "$snplocations" "$TMPDIR"/.

for lzresults in $(cat $lzresults_list)
do
 cp results_cat/$lzresults "$TMPDIR"/.

 echo "Filtering data to columns 1 and $pcolnum"
 zcat "$TMPDIR"/"$lzresults" | awk -v pcolnum=$pcolnum '{print $1,$pcolnum}'  | LC_ALL=C sort -k1,1b > "$TMPDIR"/"$lzresults".temp.txt

 echo "Joining to reference locations"
  LC_ALL=C join "$TMPDIR"/"$snplocations" "$TMPDIR"/"$lzresults".temp.txt > "$TMPDIR"/"$lzresults".lz

 echo MarkerName P.value > "$TMPDIR"/lz.header

 #for each chromosome, make a file (will be parsable)
 for chr in 3 # 12 19 14 18 # 1 6 9 13 #{1..22}
 do
  echo "printing results for $chr"
  awk -v chr=$chr '{if ($2 == chr) print $1,$4}' "$TMPDIR"/"$lzresults".lz  > results_lz/"$lzresults"."$chr".lz
 done
done

