#!/bin/bash
#PBS -V

while getopts m:s:l:d:c:p: option
do
  case "${option}"
    in
      m) mhplotscript=${OPTARG};;
      s) graphicsscript=${OPTARG};;
      l) snplocations=${OPTARG};;
      d) metaresults_list=${OPTARG};;
      c) color=${OPTARG};;
      p) pvalinclude=${OPTARG};;   
    esac
done

cp $snplocations "$TMPDIR"/"$snplocations"
#Load R
module load R 
#Take the line of metal results

jstart=$((($PBS_ARRAYID-1)*16 +1))
jstop=$(($PBS_ARRAYID*16))


awk -v jstart=$jstart -v jstop=$jstop '{if (NR >= jstart && NR <= jstop) print }' $metaresults_list > errandout/mh_job_"$PBS_ARRAYID"


for filein in $(cat errandout/mh_job_"$PBS_ARRAYID")
do

echo "Filtering data to columns 1 and 6 (metal defaults). Only take results with p < $pvalinclude"
 cut -f 1,6 results_cat/$filein | awk -v pvalinclude=$pvalinclude '{if ($2 < pvalinclude) print}' | LC_ALL=C sort -k1,1b > "$TMPDIR"/"$filein".temp.txt

echo "Joining to reference locations"
 LC_ALL=C join $snplocations "$TMPDIR"/"$filein".temp.txt > "$TMPDIR"/"$filein".temp2.txt

echo "Starting Manhattan plotting script"
Rscript $mhplotscript $graphicsscript "$TMPDIR"/"$filein".temp2.txt plots/"$filein".jpg $color &

done
wait