#!/bin/bash
#PBS -V

while getopts q:e:p: option
do
  case "${option}"
    in
      q) qqplotscript=${OPTARG};;
      e) errorbars=${OPTARG};;
      p) pvals=${OPTARG};;   
    esac
done

#Load R
module load R 


for i in $(cat $pvals)
do
 cp results_cat/"$i"* "$TMPDIR"/. 
 
 gzip -d "$TMPDIR"/*.gz #Will unzip file in tmpdir, if zipped
 echo "QQ plotting script"
 /sara/sw/R-3.2.1/bin/Rscript $qqplotscript "$TMPDIR"/"$i" plots/"$i".qq $errorbars & 

done

wait

